name: crates

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BASENAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  core:
    env:
      CRATE_NAME: ${{ github.event.repository.name }}-${{ matrix.suffix }}
    name: Publish (${{ matrix.suffix }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [ core ]
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          key: cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
            target/release
          restore-keys: |
            cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
            cargo-${{ runner.os }}-stable-
            cargo-${{ runner.os }}-
      - run: cargo publish --all-features -v -p ${{ env.CRATE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    env:
      CRATE_NAME: ${{ github.event.repository.name }}-${{ matrix.suffix }}
    name: Publish (${{ matrix.suffix }})
    needs: [ core ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [ anim ]
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          key: cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
            target/release
          restore-keys: |
            cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
            cargo-${{ runner.os }}-stable-
            cargo-${{ runner.os }}-
      - run: cargo publish --all-features -v -p ${{ env.CRATE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish SDK
    needs: [ core, features ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          restore-keys: |
            cargo-${{ runner.os }}-stable-${{ hashFiles('**/Cargo.lock') }}
            cargo-${{ runner.os }}-stable-
            cargo-${{ runner.os }}-
      - run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}